version: '3'

services:
  backend_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    image: flask-app:latest
    container_name: flask-container
    volumes:
        - ./flask_app/:/usr/local/flask_app
    ports:
      - 8000:8000 # localport:dockerport
    command: /usr/local/bin/gunicorn run:app -b 0.0.0.0:8000 --chdir /usr/local/flask_app/

  reverse_proxy:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    image: lua-reverse-proxy:latest
    container_name: reverse-proxy-container
    volumes:
      - ./reverse_proxy/:/usr/local/openresty/reverse_proxy
    ports:
      - 80:80 # localport:dockerport

